apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gym-frontend-ingress
  namespace: gym
  annotations:
    managed-by: kustomize
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: gym.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gym-frontend-service
                port:
                  number: 80