apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gym

resources:
  - ../../base

patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml

images:
  - name: your-dockerhub-username/gym-frontend
    newTag: main